# Generated by Django 5.1.2 on 2024-10-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE sentences (
                    id INTEGER PRIMARY KEY,
                    language TEXT NOT NULL,
                    english TEXT NOT NULL,
                    translation TEXT NOT NULL,
                    topic TEXT NOT NULL
                );""",
            reverse_sql="DROP TABLE sentences;",
        ),
        migrations.RunSQL(
            sql="""
                CREATE TABLE word_scores (
                    id INTEGER PRIMARY_KEY,
                    language TEXT NOT NULL,
                    word TEXT NOT NULL,
                    score FLOAT NOT NULL,
                    last_seen DATETIME NOT NULL
                )""",
            reverse_sql="DROP TABLE word_scores;",
        ),
    ]
